DROP TABLE Mount CASCADE CONSTRAINTS;
CREATE TABLE Mount (
	mount_key	    VARCHAR2(4000) PRIMARY KEY,
	mount_name  	VARCHAR2(4000),
	mount_100rs	    VARCHAR2(4000),
	mount_area	    VARCHAR2(4000),
	mount_height	VARCHAR2(4000),
	mount_point 	VARCHAR2(4000),
	mount_inf   	VARCHAR2(4000),
	mount_transport	VARCHAR2(4000)
);

DROP SEQUENCE mount_key;
CREATE SEQUENCE mount_key;

INSERT INTO Mount (
    mount_key, 
    mount_name, 
    mount_100rs, 
    mount_area,
    mount_height, 
    mount_point, 
    mount_inf, 
    mount_transport
) VALUES(
    mount_key.NEXTVAL, 
    '백암산', 
    '100대 명산 선정이유', 
    '충청북도', 
    '1500', 
    '정상에서 바라본 구름이 절경', 
    '케이블카 타고 올라오면 편합니다', 
    '근처 터미널에서 10분 택시 타시면 빠릅니다.'
);

COMMIT;

SELECT * FROM Mount;


DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    ID VARCHAR2(50) PRIMARY KEY,
    PW VARCHAR2(50) ,
    NAME VARCHAR2(20),
    TELL VARCHAR2(30),
    FIELD VARCHAR2(100)
    
);

DROP SEQUENCE SEQ_UNO;
CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER (
    ID, 
    PW, 
    NAME, 
    TELL,
    FIELD
) VALUES(
    'admin', 
    '1234', 
    '관리자', 
    '010-1234-4341',
    NULL    
);

COMMIT;

SELECT * FROM MEMBER;




DROP TABLE Stamp_Post CASCADE CONSTRAINTS;
CREATE TABLE Stamp_Post (
	stamp_key	    VARCHAR2(4000) PRIMARY KEY,
	stmap_title 	VARCHAR2(4000),
	stamp_content	VARCHAR2(4000),
	stamp_100name	VARCHAR2(4000),
	stamp_date	    VARCHAR2(4000),
	stamp_file1	    VARCHAR2(4000),
	stamp_file2	    VARCHAR2(4000),
	stamp_file3	    VARCHAR2(4000),
	stamp_file4	    VARCHAR2(4000),
	stamp_file5	    VARCHAR2(4000),
	stamp_yesno	    VARCHAR2(4000),
	id	            VARCHAR2(4000),
    FOREIGN KEY(ID) REFERENCES MEMBER (ID) ON DELETE CASCADE
);

DROP TABLE Load CASCADE CONSTRAINTS;
CREATE TABLE Load (
	load_key	        VARCHAR2(4000) PRIMARY KEY,
	load_catogory       VARCHAR2(4000),
	load_name	        VARCHAR2(4000),
	load_address	    VARCHAR2(4000),
	load_waypoint	    VARCHAR2(4000),
	load_intro	        VARCHAR2(4000),
	load_detail_intro   VARCHAR2(4000),
	load_start	        VARCHAR2(4000),
	load_end	        VARCHAR2(4000),
	mount_key	        VARCHAR2(4000),
    FOREIGN KEY (MOUNT_KEY) REFERENCES MOUNT (MOUNT_KEY) ON DELETE SET NULL
);

DROP TABLE LoadNMount_Review CASCADE CONSTRAINTS;
CREATE TABLE LoadNMount_Review (
	lnm_key 	VARCHAR2(4000) PRIMARY KEY,
	load_key	VARCHAR2(4000),
	lnm_scope	VARCHAR2(4000),
	lnm_content	VARCHAR2(4000),
	id      	VARCHAR2(4000),
    FOREIGN KEY (LOAD_KEY) REFERENCES LOAD (LOAD_KEY) ON DELETE SET NULL,
    FOREIGN KEY(ID) REFERENCES MEMBER (ID) ON DELETE CASCADE
);

DROP TABLE Route CASCADE CONSTRAINTS;
CREATE TABLE Route (
	load_key	        VARCHAR2(4000) PRIMARY KEY,
	route_coordinates	VARCHAR2(4000),
	route_url	        VARCHAR2(4000),
    CONSTRAINT FK_LOAD_KEY FOREIGN KEY (LOAD_KEY) REFERENCES LOAD (LOAD_KEY) ON DELETE CASCADE
);

DROP TABLE POST CASCADE CONSTRAINTS;
CREATE TABLE POST (	
    POST_NUM NUMBER PRIMARY KEY,
	TITLE VARCHAR2(100), 
	CONTENT VARCHAR2(1000), 
	TYPE VARCHAR2(100),
    READCOUNT NUMBER DEFAULT 0,
    FIELD1 VARCHAR2(100),
    FIELD2 VARCHAR2(100),
    FIELD3 VARCHAR2(100),
    FIELD4 VARCHAR2(100),
    FIELD5 VARCHAR2(100),
    ID VARCHAR2(50),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE SET NULL
);
DROP SEQUENCE SEQ_POST_NUM;
CREATE SEQUENCE SEQ_POST_NUM;

DROP TABLE COMENT CASCADE CONSTRAINTS;   
CREATE TABLE COMENT(
  COMENT_KEY NUMBER PRIMARY KEY,
  COMENT_CONTENT VARCHAR2(1000),
  COMENT_DATE DATE DEFAULT SYSDATE,
  POST_NUM NUMBER,
  ID VARCHAR2(50),
  FOREIGN KEY (POST_NUM) REFERENCES POST on DELETE CASCADE,
  FOREIGN KEY (ID) REFERENCES MEMBER on DELETE CASCADE
);   
DROP SEQUENCE SEQ_COMENT_KEY;
CREATE SEQUENCE SEQ_COMENT_KEY;

DROP TABLE FOREST CASCADE CONSTRAINTS;  
CREATE TABLE FOREST(
  FOREST_KEY NUMBER PRIMARY KEY,
  FOREST_NAME VARCHAR2(50),
  FOREST_CATEGORY VARCHAR2(10),
  FOREST_OPER VARCHAR2(10),
  FOREST_INFO VARCHAR2(300),
  FOREST_CITYNAME VARCHAR2(30),
  FOREST_ADDR VARCHAR2(200),
  FOREST_PHONE VARCHAR2(50),
  CHECK_IN VARCHAR2(50),
  CHECK_OUT VARCHAR2(50),
  PERSON VARCHAR2(50),
  AMENITIES VARCHAR2(100),
  URL VARCHAR2(500),
  LATITUDE VARCHAR2(50),
  LONGITUDE VARCHAR2(50)
);   
DROP SEQUENCE SEQ_FOREST_KEY;
CREATE SEQUENCE SEQ_FOREST_KEY;

DROP TABLE ROOM CASCADE CONSTRAINTS;  
CREATE TABLE ROOM(
  ROOM_KEY NUMBER PRIMARY KEY,
  ROOM_NAME VARCHAR2(50),
  PERSON VARCHAR2(10),
  MAX_PERSON VARCHAR2(10),
  ROOM_SIZE VARCHAR2(20),
  AMENITIES VARCHAR2(100),
  ROOM_PURPOSE VARCHAR2(20),
  CHECK_IN VARCHAR2(20),
  CHECK_OUT VARCHAR2(20),
  OFF_WEEKDAY VARCHAR2(100),
  OFFWEEKEND VARCHAR2(100),
  ON_WEEKDAY VARCHAR2(100),
  ON_WEEKEND VARCHAR2(100),
  CAUTION VARCHAR2(200),
  GUIDE VARCHAR2(200),
  MATERIAL VARCHAR2(100),
  FOREST_KEY NUMBER,
  FOREIGN KEY (FOREST_KEY) REFERENCES FOREST on DELETE CASCADE
); 

DROP TABLE BOOK CASCADE CONSTRAINTS;  
CREATE TABLE BOOK(
  BOOK_KEY NUMBER PRIMARY KEY,
  PERSON VARCHAR2(10),
  CHECK_IN VARCHAR2(20),
  CHECK_OUT VARCHAR2(20),
  PAY VARCHAR2(10),
  ID VARCHAR2(50),
  ROOM_KEY NUMBER,
  FOREIGN KEY (ID) REFERENCES MEMBER on DELETE SET NULL,
  FOREIGN KEY (ROOM_KEY) REFERENCES ROOM on DELETE SET NULL
);

DROP TABLE FOREST_REVIEW CASCADE CONSTRAINTS; 
CREATE TABLE FOREST_REVIEW(
  FR_KEY NUMBER PRIMARY KEY,
  FR_SCOPE VARCHAR2(10),
  FR_CONTENT VARCHAR2(500),
  FR_FACILITY VARCHAR2(100),
  ID VARCHAR2(50),
  ROOM_KEY NUMBER,
  FOREIGN KEY (ID) REFERENCES MEMBER on DELETE SET NULL,
  FOREIGN KEY (ROOM_KEY) REFERENCES ROOM on DELETE SET NULL
);
